export const categories = [
  "Technology",
  "Science",
  "Health",
  "Finance",
  "Education",
  "Travel",
  "Food",
  "Fitness",
  "Programming",
  "Design",
  "Music",
  "Movies",
  "Art",
  "History",
  "Politics",
  "Gaming",
  "Photography",
  "Business",
  "Marketing",
  "Lifestyle",
  "Fashion",
  "Parenting",
  "DIY",
  "Culture",
  "Nature",
  "Animals",
  "Spirituality",
  "Sports",
  "Books",
  "Writing",
  "Productivity",
  "Career",
  "Relationships",
  "Events",
  "News",
  "Environment",
  "Astrology",
  "Startups",
  "AI",
  "Machine Learning",
  "Cybersecurity",
  "Blockchain",
  "Economy",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Astronomy",
  "Statistics",
  "Data Science",
  "Web Development",
  "Mobile Development",
  "DevOps",
  "Cloud Computing",
  "AR/VR",
  "E-commerce",
  "UI/UX",
  "Animation",
  "Graphic Design",
  "Interior Design",
  "Architecture",
  "Engineering",
  "Automotive",
  "Agriculture",
  "Gardening",
  "Real Estate",
  "Legal",
  "Logistics",
  "Project Management",
  "Human Resources",
  "Recruiting",
  "Freelancing",
  "Remote Work",
  "Self Improvement",
  "Motivation",
  "Mindfulness",
  "Meditation",
  "Philosophy",
  "Psychology",
  "Sociology",
  "Ethics",
  "Religion",
  "Languages",
  "Translation",
  "Culinary Arts",
  "Baking",
  "Wine",
  "Coffee",
  "Tea",
  "Pets",
  "Bird Watching",
  "Hiking",
  "Camping",
  "Fishing",
  "Hunting",
  "Survival",
  "Crafts",
  "Sewing",
  "Woodworking",
  "3D Printing",
];
